services:
  mongodb:
    image: mongo:7
    container_name: delivery_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: delivery_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongo_data: